-- AlterTable
ALTER TABLE "class_students"
ADD COLUMN "u1" DOUBLE PRECISION,
ADD COLUMN "u2" DOUBLE PRECISION,
ADD COLUMN "u3" DOUBLE PRECISION,
ADD COLUMN "recoveryExam" DOUBLE PRECISION,
ADD COLUMN "finalExam" DOUBLE PRECISION;
